apiVersion: v1
kind: Namespace
metadata:
  name: meetinity-prod
  labels:
    app.kubernetes.io/part-of: meetinity
    meetinity.io/environment: prod
    networking.meetinity.io/ingress-allowed: "true"
  annotations:
    meetinity.io/purpose: production workloads for Meetinity
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: meetinity-prod-compute
  namespace: meetinity-prod
spec:
  hard:
    requests.cpu: "16"
    requests.memory: 32Gi
    limits.cpu: "24"
    limits.memory: 48Gi
    pods: "120"
    services.loadbalancers: "6"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: meetinity-prod-defaults
  namespace: meetinity-prod
spec:
  limits:
    - type: Container
      default:
        cpu: 1
        memory: 1Gi
      defaultRequest:
        cpu: 250m
        memory: 384Mi
      max:
        cpu: "6"
        memory: 8Gi
      min:
        cpu: 150m
        memory: 256Mi
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: meetinity-prod-default
  namespace: meetinity-prod
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              meetinity.io/environment: prod
        - namespaceSelector:
            matchLabels:
              networking.meetinity.io/ingress-allowed: "true"
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              meetinity.io/environment: prod
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80
