apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: monitoring
type: Opaque
stringData:
  alertmanager.yaml: |
    route:
      receiver: default
      group_by: ['alertname','cluster']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
    receivers:
      - name: default
        slack_configs:
          - channel: '#meetinity-alerts'
            send_resolved: true
            api_url: ${SLACK_WEBHOOK_URL}
        email_configs:
          - to: sre@meetinity.com
            send_resolved: true
    inhibit_rules:
      - source_matchers: ['severity = critical']
        target_matchers: ['severity = warning']
        equal: ['alertname', 'namespace']
