apiVersion: v2
name: api-gateway
description: Deploys the Meetinity API Gateway service.
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: common
    version: 0.1.0
    repository: "file://../common"
