apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "user-service.fullname" . }}
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "user-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "user-service.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "user-service.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- $env := list }}
          {{- range $index, $item := (.Values.env | default list) }}
          {{- $env = append $env $item }}
          {{- end }}
          {{- $dbConfig := default (dict) (get .Values.global "database") }}
          {{- $dbSecretName := default "" (get $dbConfig "secretName") }}
          {{- $dbSecretKeys := default (dict) (get $dbConfig "secretKeys") }}
          {{- $dbUrlKey := default "" (get $dbSecretKeys "url") }}
          {{- if and $dbSecretName $dbUrlKey }}
          {{- $env = append $env (dict "name" "DATABASE_URL" "valueFrom" (dict "secretKeyRef" (dict "name" $dbSecretName "key" $dbUrlKey))) }}
          {{- end }}
          {{- if gt (len $env) 0 }}
          env:
            {{- toYaml $env | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- include "common.httpProbes" (dict "port" .Values.service.port "liveness" .Values.livenessProbe "readiness" .Values.readinessProbe) | nindent 10 }}
