fullnameOverride: kibana

replicaCount: 2

image:
  repository: docker.elastic.co/kibana/kibana
  tag: 8.12.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5601

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  hosts:
    - host: kibana.meetinity.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - kibana.meetinity.com
      secretName: kibana-tls

kibanaConfig:
  kibana.yml: |
    server.publicBaseUrl: https://kibana.meetinity.com
    elasticsearch.hosts: ["https://elasticsearch-master.logging.svc.cluster.local:9200"]
    elasticsearch.username: kibana_system
    elasticsearch.password: ${KIBANA_SYSTEM_PASSWORD}
    monitoring.ui.container.elasticsearch.enabled: true
    xpack.security.enabled: true
    xpack.encryptedSavedObjects.encryptionKey: ${KIBANA_ENCRYPTION_KEY}

extraEnvs:
  - name: KIBANA_SYSTEM_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: kibanaSystemPassword
  - name: KIBANA_ENCRYPTION_KEY
    valueFrom:
      secretKeyRef:
        name: kibana-secrets
        key: encryptionKey

resources:
  requests:
    cpu: 200m
    memory: 1Gi
  limits:
    cpu: 1
    memory: 2Gi
