global:
  environment: dev
  domain: dev.meetinity.internal
  secretStores:
    default:
      name: vault-dev
      kind: ClusterSecretStore

shared:
  configMaps:
    platform-settings:
      data:
        FEATURE_FLAGS: "true"
        DEFAULT_TIMEZONE: "UTC"

api-gateway:
  environment: dev
  domain: dev.meetinity.internal
  replicaCount: 1
  image:
    tag: dev
  ingress:
    tlsSecretName: api-gateway-dev-tls
  autoscaling:
    minReplicas: 1
    maxReplicas: 3
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 60
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 70
  resources:
    requests:
      cpu: 150m
      memory: 192Mi
    limits:
      cpu: 300m
      memory: 384Mi
  podDisruptionBudget:
    minAvailable: 1
  env:
    - name: LOG_LEVEL
      value: info
  sealedSecrets:
    - name: api-gateway-tls
      encryptedData:
        tls.crt: PLACEHOLDER_DEV_CERT
        tls.key: PLACEHOLDER_DEV_KEY

user-service:
  environment: dev
  domain: dev.meetinity.internal
  replicaCount: 1
  autoscaling:
    minReplicas: 1
    maxReplicas: 3
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 60
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 70
  resources:
    requests:
      cpu: 120m
      memory: 192Mi
    limits:
      cpu: 250m
      memory: 384Mi
  podDisruptionBudget:
    minAvailable: 1

matching-service:
  environment: dev
  domain: dev.meetinity.internal
  replicaCount: 1
  autoscaling:
    minReplicas: 1
    maxReplicas: 2
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 55
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 65
  resources:
    requests:
      cpu: 120m
      memory: 192Mi
    limits:
      cpu: 250m
      memory: 384Mi
  podDisruptionBudget:
    minAvailable: 1
  vaultSecrets:
    - name: matching-service-env
      path: kv/data/dev/matching-service/app
      secretStoreRef:
        name: vault-dev
      target:
        template:
          type: Opaque
          data:
            MATCHING_THRESHOLD: '{{ .data.matching_threshold | default "0.75" }}'

event-service:
  environment: dev
  domain: dev.meetinity.internal
  replicaCount: 1
  autoscaling:
    minReplicas: 1
    maxReplicas: 3
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 55
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 65
  resources:
    requests:
      cpu: 120m
      memory: 192Mi
    limits:
      cpu: 250m
      memory: 384Mi
  podDisruptionBudget:
    minAvailable: 1
  vaultSecrets:
    - name: event-service-env
      path: kv/data/dev/event-service/app
      secretStoreRef:
        name: vault-dev
      target:
        template:
          type: Opaque
          data:
            EVENT_CATALOG_URL: '{{ .data.catalog_url }}'
