global:
  environment: dev
  domain: dev.meetinity.internal
  secretStores:
    default:
      name: vault-dev
      kind: ClusterSecretStore
      spec:
        provider:
          vault:
            server: https://vault.dev.meetinity.internal
            auth:
              kubernetes:
                role: meetinity-dev

shared:
  configMaps:
    platform-settings:
      data:
        FEATURE_FLAGS: "true"
        DEFAULT_TIMEZONE: "UTC"

api-gateway:
  environment: dev
  domain: dev.meetinity.internal
  replicaCount: 1
  image:
    tag: dev
  ingress:
    tlsSecretName: api-gateway-dev-tls
  autoscaling:
    minReplicas: 1
    maxReplicas: 3
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 60
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 70
  resources:
    requests:
      cpu: 150m
      memory: 192Mi
    limits:
      cpu: 300m
      memory: 384Mi
  podDisruptionBudget:
    minAvailable: 1
  env:
    - name: LOG_LEVEL
      value: info
  vaultSecrets:
    - name: api-gateway-tls
      path: "kv/data/dev/ingress/api-gateway"
      target:
        name: api-gateway-dev-tls
        creationPolicy: Owner
        template:
          type: kubernetes.io/tls

user-service:
  environment: dev
  domain: dev.meetinity.internal
  replicaCount: 1
  autoscaling:
    minReplicas: 1
    maxReplicas: 3
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 60
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 70
  resources:
    requests:
      cpu: 120m
      memory: 192Mi
    limits:
      cpu: 250m
      memory: 384Mi
  podDisruptionBudget:
    minAvailable: 1

matching-service:
  environment: dev
  domain: dev.meetinity.internal
  replicaCount: 1
  autoscaling:
    minReplicas: 1
    maxReplicas: 2
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 55
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 65
  resources:
    requests:
      cpu: 120m
      memory: 192Mi
    limits:
      cpu: 250m
      memory: 384Mi
  podDisruptionBudget:
    minAvailable: 1
  vaultSecrets:
    - name: matching-service-env
      path: kv/data/dev/matching-service/app
      secretStoreRef:
        name: vault-dev
      target:
        template:
          type: Opaque
          data:
            MATCHING_THRESHOLD: '{{ .data.matching_threshold | default "0.75" }}'

event-service:
  environment: dev
  domain: dev.meetinity.internal
  replicaCount: 1
  autoscaling:
    minReplicas: 1
    maxReplicas: 3
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 55
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 65
  resources:
    requests:
      cpu: 120m
      memory: 192Mi
    limits:
      cpu: 250m
      memory: 384Mi
  podDisruptionBudget:
    minAvailable: 1
  vaultSecrets:
    - name: event-service-env
      path: kv/data/dev/event-service/app
      secretStoreRef:
        name: vault-dev
      target:
        template:
          type: Opaque
          data:
            EVENT_CATALOG_URL: '{{ .data.catalog_url }}'

notification-service:
  environment: dev
  domain: dev.meetinity.internal
  replicaCount: 1
  autoscaling:
    minReplicas: 1
    maxReplicas: 2
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 55
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 65
  resources:
    requests:
      cpu: 120m
      memory: 192Mi
    limits:
      cpu: 250m
      memory: 384Mi
  podDisruptionBudget:
    minAvailable: 1
  vaultSecrets:
    - name: notification-service-env
      path: kv/data/dev/notification-service/app
      secretStoreRef:
        name: vault-dev
      target:
        template:
          type: Opaque
          data:
            DATABASE_URL: '{{ .data.database_url | default "" }}'
            REDIS_URL: '{{ .data.redis_url | default "redis://redis:6379/0" }}'
            KAFKA_BOOTSTRAP_SERVERS: '{{ .data.kafka_bootstrap | default "kafka:9092" }}'
            KAFKA_NOTIFICATION_TOPIC: '{{ .data.kafka_topic | default "notifications.dispatch" }}'
