global:
  environment: dev
  domain: dev.meetinity.internal
  secretStores:
    default:
      name: vault-dev
      kind: ClusterSecretStore
      spec:
        provider:
          vault:
            server: https://vault.dev.meetinity.internal
            auth:
              kubernetes:
                role: meetinity-dev

shared:
  configMaps:
    platform-settings:
      data:
        FEATURE_FLAGS: "true"
        DEFAULT_TIMEZONE: "UTC"
  vaultSecrets:
    - name: shared-kafka
      path: "kv/data/{{ .Values.global.environment }}/shared/kafka"
      target:
        name: meetinity-shared-kafka
        creationPolicy: Owner
        template:
          type: Opaque

api-gateway:
  environment: dev
  domain: dev.meetinity.internal
  replicaCount: 1
  image:
    tag: dev
  ingress:
    tlsSecretName: api-gateway-dev-tls
  autoscaling:
    minReplicas: 1
    maxReplicas: 3
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 60
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 70
  resources:
    requests:
      cpu: 150m
      memory: 192Mi
    limits:
      cpu: 300m
      memory: 384Mi
  podDisruptionBudget:
    minAvailable: 1
  env:
    - name: LOG_LEVEL
      value: info
  vaultSecrets:
    - name: api-gateway-tls
      path: "kv/data/dev/ingress/api-gateway"
      target:
        name: api-gateway-dev-tls
        creationPolicy: Owner
        template:
          type: kubernetes.io/tls

user-service:
  environment: dev
  domain: dev.meetinity.internal
  replicaCount: 1
  autoscaling:
    minReplicas: 1
    maxReplicas: 3
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 60
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 70
  resources:
    requests:
      cpu: 120m
      memory: 192Mi
    limits:
      cpu: 250m
      memory: 384Mi
  podDisruptionBudget:
    minAvailable: 1

matching-service:
  environment: dev
  domain: dev.meetinity.internal
  replicaCount: 1
  autoscaling:
    minReplicas: 1
    maxReplicas: 2
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 55
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 65
  resources:
    requests:
      cpu: 120m
      memory: 192Mi
    limits:
      cpu: 250m
      memory: 384Mi
  podDisruptionBudget:
    minAvailable: 1
  vaultSecrets:
    - name: matching-service-env
      path: kv/data/dev/matching-service/app
      secretStoreRef:
        name: vault-dev
      target:
        template:
          type: Opaque
          data:
            MATCHING_THRESHOLD: '{{ .data.matching_threshold | default "0.75" }}'

event-service:
  environment: dev
  domain: dev.meetinity.internal
  replicaCount: 1
  autoscaling:
    minReplicas: 1
    maxReplicas: 3
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 55
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 65
  resources:
    requests:
      cpu: 120m
      memory: 192Mi
    limits:
      cpu: 250m
      memory: 384Mi
  podDisruptionBudget:
    minAvailable: 1
  vaultSecrets:
    - name: event-service-env
      path: kv/data/dev/event-service/app
      secretStoreRef:
        name: vault-dev
      target:
        template:
          type: Opaque
          data:
            EVENT_CATALOG_URL: '{{ .data.catalog_url }}'
            MODERATION_SERVICE_URL: '{{ .data.moderation_url | default "http://moderation-service:8080" }}'

notification-service:
  environment: dev
  domain: dev.meetinity.internal
  replicaCount: 1
  autoscaling:
    minReplicas: 1
    maxReplicas: 2
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 55
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 65
  resources:
    requests:
      cpu: 120m
      memory: 192Mi
    limits:
      cpu: 250m
      memory: 384Mi
  podDisruptionBudget:
    minAvailable: 1
  vaultSecrets:
    - name: notification-service-env
      path: kv/data/dev/notification-service/app
      secretStoreRef:
        name: vault-dev
      target:
        template:
          type: Opaque
          data:
            DATABASE_URL: '{{ .data.database_url | default "" }}'
            REDIS_URL: '{{ .data.redis_url | default "redis://redis:6379/0" }}'
            KAFKA_BOOTSTRAP_SERVERS: '{{ .data.kafka_bootstrap | default "kafka:9092" }}'
            KAFKA_NOTIFICATION_TOPIC: '{{ .data.kafka_topic | default "notifications.dispatch" }}'
            KAFKA_SCHEMA_REGISTRY_URL: '{{ .data.kafka_schema_registry | default "" }}'
            KAFKA_SECURITY_PROTOCOL: '{{ .data.kafka_security_protocol | default "" }}'
            KAFKA_SASL_MECHANISM: '{{ .data.kafka_sasl_mechanism | default "" }}'
            KAFKA_SASL_USERNAME: '{{ .data.kafka_sasl_username | default "" }}'
            KAFKA_SASL_PASSWORD: '{{ .data.kafka_sasl_password | default "" }}'
            KAFKA_DLQ_TOPIC: '{{ .data.kafka_dlq_topic | default "notifications.dispatch.dlq" }}'

moderation-service:
  environment: dev
  domain: dev.meetinity.internal
  replicaCount: 1
  autoscaling:
    minReplicas: 1
    maxReplicas: 2
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 55
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 65
  resources:
    requests:
      cpu: 120m
      memory: 192Mi
    limits:
      cpu: 250m
      memory: 384Mi
  podDisruptionBudget:
    minAvailable: 1
  vaultSecrets:
    - name: moderation-service-env
      path: kv/data/dev/moderation-service/app
      secretStoreRef:
        name: vault-dev
      target:
        template:
          type: Opaque
          data:
            DATABASE_URL: '{{ .data.database_url | default "" }}'
            REDIS_URL: '{{ .data.redis_url | default "redis://redis:6379/1" }}'
            KAFKA_BOOTSTRAP_SERVERS: '{{ .data.kafka_bootstrap | default "kafka:9092" }}'
            KAFKA_MODERATION_TOPIC: '{{ .data.kafka_topic | default "moderation.events" }}'
            KAFKA_SCHEMA_REGISTRY_URL: '{{ .data.kafka_schema_registry | default "" }}'
            KAFKA_SECURITY_PROTOCOL: '{{ .data.kafka_security_protocol | default "" }}'
            KAFKA_SASL_MECHANISM: '{{ .data.kafka_sasl_mechanism | default "" }}'
            KAFKA_SASL_USERNAME: '{{ .data.kafka_sasl_username | default "" }}'
            KAFKA_SASL_PASSWORD: '{{ .data.kafka_sasl_password | default "" }}'
            KAFKA_DLQ_TOPIC: '{{ .data.kafka_dlq_topic | default "moderation.events.dlq" }}'
            ML_CLASSIFIER_URL: '{{ .data.ml_classifier_url | default "" }}'

search-service:
  environment: dev
  domain: dev.meetinity.internal
  replicaCount: 1
  autoscaling:
    minReplicas: 1
    maxReplicas: 2
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 60
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 70
  resources:
    requests:
      cpu: 120m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi
  podDisruptionBudget:
    minAvailable: 1
  env:
    - name: SEARCH_NODES
      value: https://search.dev.meetinity.internal
    - name: SEARCH_VERIFY_CERTS
      value: "1"
    - name: SEARCH_TIMEOUT
      value: "10"
  vaultSecrets:
    - name: search-service-opensearch
      path: kv/data/dev/search-service/opensearch
      secretStoreRef:
        name: vault-dev
      target:
        template:
          type: Opaque
          data:
            SEARCH_USERNAME: '{{ .data.username | default "" }}'
            SEARCH_PASSWORD: '{{ .data.password | default "" }}'
