global:
  environment: prod
  domain: meetinity.com
  secretStores:
    default:
      name: vault-prod
      kind: ClusterSecretStore

shared:
  configMaps:
    platform-settings:
      data:
        FEATURE_FLAGS: "false"
        DEFAULT_TIMEZONE: "UTC"
  sealedSecrets:
    - name: platform-tls
      encryptedData:
        tls.crt: PLACEHOLDER_PROD_CERT
        tls.key: PLACEHOLDER_PROD_KEY
  vaultSecrets:
    - name: platform-database
      path: kv/data/prod/platform/database
      secretStoreRef:
        name: vault-prod
      target:
        template:
          type: Opaque
          data:
            DATABASE_URL: '{{ .data.database_url }}'

api-gateway:
  environment: prod
  domain: meetinity.com
  replicaCount: 4
  image:
    tag: v1.0.0
  autoscaling:
    minReplicas: 4
    maxReplicas: 12
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 70
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 80
      - type: Pods
        pods:
          metric:
            name: http_requests_per_second
          target:
            type: AverageValue
            averageValue: "60"
  resources:
    requests:
      cpu: 600m
      memory: 768Mi
    limits:
      cpu: 1200m
      memory: 1536Mi
  podDisruptionBudget:
    minAvailable: 2
  vpa:
    enabled: true
    updatePolicy:
      updateMode: "Off"
    resourcePolicy:
      containerPolicies:
        - containerName: "*"
          minAllowed:
            cpu: 400m
            memory: 512Mi
          maxAllowed:
            cpu: 3000m
            memory: 4Gi
  vaultSecrets:
    - name: api-gateway-env
      path: kv/data/prod/api-gateway/app
      secretStoreRef:
        name: vault-prod
      target:
        template:
          type: Opaque
          data:
            DATABASE_URL: '{{ .data.database_url }}'
            REDIS_URL: '{{ .data.redis_url }}'
            LOG_LEVEL: '{{ .data.log_level | default "warn" }}'

user-service:
  environment: prod
  domain: meetinity.com
  replicaCount: 3
  autoscaling:
    minReplicas: 3
    maxReplicas: 8
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 65
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 75
      - type: Pods
        pods:
          metric:
            name: user_profile_sync_per_second
          target:
            type: AverageValue
            averageValue: "20"
  resources:
    requests:
      cpu: 350m
      memory: 448Mi
    limits:
      cpu: 800m
      memory: 896Mi
  podDisruptionBudget:
    minAvailable: 2
  vpa:
    enabled: true
    updatePolicy:
      updateMode: "Off"
    resourcePolicy:
      containerPolicies:
        - containerName: "*"
          minAllowed:
            cpu: 300m
            memory: 384Mi
          maxAllowed:
            cpu: 2000m
            memory: 3Gi
  vaultSecrets:
    - name: user-service-db
      path: kv/data/prod/user-service/database
      secretStoreRef:
        name: vault-prod
      target:
        template:
          type: Opaque
          data:
            url: '{{ .data.url }}'

matching-service:
  environment: prod
  domain: meetinity.com
  replicaCount: 3
  autoscaling:
    minReplicas: 2
    maxReplicas: 6
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 65
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 75
      - type: Pods
        pods:
          metric:
            name: matches_computed_per_second
          target:
            type: AverageValue
            averageValue: "25"
  resources:
    requests:
      cpu: 350m
      memory: 448Mi
    limits:
      cpu: 800m
      memory: 896Mi
  podDisruptionBudget:
    minAvailable: 2
  vpa:
    enabled: true
    updatePolicy:
      updateMode: "Off"
    resourcePolicy:
      containerPolicies:
        - containerName: "*"
          minAllowed:
            cpu: 300m
            memory: 384Mi
          maxAllowed:
            cpu: 2000m
            memory: 3Gi
  vaultSecrets:
    - name: matching-service-env
      path: kv/data/prod/matching-service/app
      secretStoreRef:
        name: vault-prod
      target:
        template:
          type: Opaque
          data:
            MATCHING_THRESHOLD: '{{ .data.matching_threshold | default "0.85" }}'

event-service:
  environment: prod
  domain: meetinity.com
  replicaCount: 3
  autoscaling:
    minReplicas: 3
    maxReplicas: 8
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 65
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 75
      - type: Pods
        pods:
          metric:
            name: events_processed_per_second
          target:
            type: AverageValue
            averageValue: "40"
  resources:
    requests:
      cpu: 350m
      memory: 512Mi
    limits:
      cpu: 900m
      memory: 1228Mi
  podDisruptionBudget:
    minAvailable: 2
  vpa:
    enabled: true
    updatePolicy:
      updateMode: "Off"
    resourcePolicy:
      containerPolicies:
        - containerName: "*"
          minAllowed:
            cpu: 300m
            memory: 384Mi
          maxAllowed:
            cpu: 2200m
            memory: 3Gi
  vaultSecrets:
    - name: event-service-env
      path: kv/data/prod/event-service/app
      secretStoreRef:
        name: vault-prod
      target:
        template:
          type: Opaque
          data:
            EVENT_CATALOG_URL: '{{ .data.catalog_url }}'
