global:
  environment: prod
  domain: meetinity.com
  secretStores:
    default:
      name: vault-prod
      kind: ClusterSecretStore
      spec:
        provider:
          vault:
            server: https://vault.meetinity.com
            auth:
              kubernetes:
                role: meetinity-prod

shared:
  configMaps:
    platform-settings:
      data:
        FEATURE_FLAGS: "false"
        DEFAULT_TIMEZONE: "UTC"
  vaultSecrets:
    - name: shared-database
      path: "kv/data/{{ .Values.global.environment }}/shared/database"
      target:
        name: meetinity-shared-database
        creationPolicy: Owner
        template:
          type: Opaque
    - name: shared-redis
      path: "kv/data/{{ .Values.global.environment }}/shared/redis"
      target:
        name: meetinity-shared-redis
        creationPolicy: Owner
        template:
          type: Opaque
    - name: shared-kafka
      path: "kv/data/{{ .Values.global.environment }}/shared/kafka"
      target:
        name: meetinity-shared-kafka
        creationPolicy: Owner
        template:
          type: Opaque
    - name: platform-tls
      path: "kv/data/{{ .Values.global.environment }}/shared/tls/platform"
      target:
        name: platform-tls
        creationPolicy: Owner
        template:
          type: kubernetes.io/tls

api-gateway:
  environment: prod
  domain: meetinity.com
  replicaCount: 4
  image:
    tag: v1.0.0
  autoscaling:
    minReplicas: 4
    maxReplicas: 12
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 70
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 80
      - type: Pods
        pods:
          metric:
            name: http_requests_per_second
          target:
            type: AverageValue
            averageValue: "60"
  resources:
    requests:
      cpu: 600m
      memory: 768Mi
    limits:
      cpu: 1200m
      memory: 1536Mi
  podDisruptionBudget:
    minAvailable: 2
  vpa:
    enabled: true
    updatePolicy:
      updateMode: "Off"
    resourcePolicy:
      containerPolicies:
        - containerName: "*"
          minAllowed:
            cpu: 400m
            memory: 512Mi
          maxAllowed:
            cpu: 3000m
            memory: 4Gi
  env:
    - name: LOG_LEVEL
      value: warn
  vaultSecrets:
    - name: api-gateway-tls
      path: "kv/data/prod/ingress/api-gateway"
      target:
        name: api-gateway-prod-tls
        creationPolicy: Owner
        template:
          type: kubernetes.io/tls

user-service:
  environment: prod
  domain: meetinity.com
  replicaCount: 3
  autoscaling:
    minReplicas: 3
    maxReplicas: 8
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 65
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 75
      - type: Pods
        pods:
          metric:
            name: user_profile_sync_per_second
          target:
            type: AverageValue
            averageValue: "20"
  resources:
    requests:
      cpu: 350m
      memory: 448Mi
    limits:
      cpu: 800m
      memory: 896Mi
  podDisruptionBudget:
    minAvailable: 2
  vpa:
    enabled: true
    updatePolicy:
      updateMode: "Off"
    resourcePolicy:
      containerPolicies:
        - containerName: "*"
          minAllowed:
            cpu: 300m
            memory: 384Mi
          maxAllowed:
            cpu: 2000m
            memory: 3Gi

matching-service:
  environment: prod
  domain: meetinity.com
  replicaCount: 3
  autoscaling:
    minReplicas: 2
    maxReplicas: 6
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 65
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 75
      - type: Pods
        pods:
          metric:
            name: matches_computed_per_second
          target:
            type: AverageValue
            averageValue: "25"
  resources:
    requests:
      cpu: 350m
      memory: 448Mi
    limits:
      cpu: 800m
      memory: 896Mi
  podDisruptionBudget:
    minAvailable: 2
  vpa:
    enabled: true
    updatePolicy:
      updateMode: "Off"
    resourcePolicy:
      containerPolicies:
        - containerName: "*"
          minAllowed:
            cpu: 300m
            memory: 384Mi
          maxAllowed:
            cpu: 2000m
            memory: 3Gi
  vaultSecrets:
    - name: matching-service-env
      path: kv/data/prod/matching-service/app
      secretStoreRef:
        name: vault-prod
      target:
        template:
          type: Opaque
          data:
            MATCHING_THRESHOLD: '{{ .data.matching_threshold | default "0.85" }}'

event-service:
  environment: prod
  domain: meetinity.com
  replicaCount: 3
  autoscaling:
    minReplicas: 3
    maxReplicas: 8
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 65
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 75
      - type: Pods
        pods:
          metric:
            name: events_processed_per_second
          target:
            type: AverageValue
            averageValue: "40"
  resources:
    requests:
      cpu: 350m
      memory: 512Mi
    limits:
      cpu: 900m
      memory: 1228Mi
  podDisruptionBudget:
    minAvailable: 2
  vpa:
    enabled: true
    updatePolicy:
      updateMode: "Off"
    resourcePolicy:
      containerPolicies:
        - containerName: "*"
          minAllowed:
            cpu: 300m
            memory: 384Mi
          maxAllowed:
            cpu: 2200m
            memory: 3Gi
  vaultSecrets:
    - name: event-service-env
      path: kv/data/prod/event-service/app
      secretStoreRef:
        name: vault-prod
      target:
        template:
          type: Opaque
          data:
            EVENT_CATALOG_URL: '{{ .data.catalog_url }}'
            MODERATION_SERVICE_URL: '{{ .data.moderation_url | default "http://moderation-service:8080" }}'

notification-service:
  environment: prod
  domain: meetinity.com
  replicaCount: 3
  autoscaling:
    minReplicas: 3
    maxReplicas: 6
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 50
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 60
  resources:
    requests:
      cpu: 250m
      memory: 320Mi
    limits:
      cpu: 500m
      memory: 640Mi
  podDisruptionBudget:
    minAvailable: 2
  vaultSecrets:
    - name: notification-service-env
      path: kv/data/prod/notification-service/app
      secretStoreRef:
        name: vault-prod
      target:
        template:
          type: Opaque
          data:
            DATABASE_URL: '{{ .data.database_url | default "" }}'
            REDIS_URL: '{{ .data.redis_url | default "redis://redis:6379/0" }}'
            KAFKA_BOOTSTRAP_SERVERS: '{{ .data.kafka_bootstrap | default "kafka:9092" }}'
            KAFKA_NOTIFICATION_TOPIC: '{{ .data.kafka_topic | default "notifications.dispatch" }}'
            KAFKA_SCHEMA_REGISTRY_URL: '{{ .data.kafka_schema_registry | default "" }}'
            KAFKA_SECURITY_PROTOCOL: '{{ .data.kafka_security_protocol | default "" }}'
            KAFKA_SASL_MECHANISM: '{{ .data.kafka_sasl_mechanism | default "" }}'
            KAFKA_SASL_USERNAME: '{{ .data.kafka_sasl_username | default "" }}'
            KAFKA_SASL_PASSWORD: '{{ .data.kafka_sasl_password | default "" }}'
            KAFKA_DLQ_TOPIC: '{{ .data.kafka_dlq_topic | default "notifications.dispatch.dlq" }}'

moderation-service:
  environment: prod
  domain: meetinity.com
  replicaCount: 3
  autoscaling:
    minReplicas: 3
    maxReplicas: 6
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 55
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 65
  resources:
    requests:
      cpu: 250m
      memory: 384Mi
    limits:
      cpu: 600m
      memory: 768Mi
  podDisruptionBudget:
    minAvailable: 2
  vaultSecrets:
    - name: moderation-service-env
      path: kv/data/prod/moderation-service/app
      secretStoreRef:
        name: vault-prod
      target:
        template:
          type: Opaque
          data:
            DATABASE_URL: '{{ .data.database_url | default "" }}'
            REDIS_URL: '{{ .data.redis_url | default "redis://redis:6379/1" }}'
            KAFKA_BOOTSTRAP_SERVERS: '{{ .data.kafka_bootstrap | default "kafka:9092" }}'
            KAFKA_MODERATION_TOPIC: '{{ .data.kafka_topic | default "moderation.events" }}'
            KAFKA_SCHEMA_REGISTRY_URL: '{{ .data.kafka_schema_registry | default "" }}'
            KAFKA_SECURITY_PROTOCOL: '{{ .data.kafka_security_protocol | default "" }}'
            KAFKA_SASL_MECHANISM: '{{ .data.kafka_sasl_mechanism | default "" }}'
            KAFKA_SASL_USERNAME: '{{ .data.kafka_sasl_username | default "" }}'
            KAFKA_SASL_PASSWORD: '{{ .data.kafka_sasl_password | default "" }}'
            KAFKA_DLQ_TOPIC: '{{ .data.kafka_dlq_topic | default "moderation.events.dlq" }}'
            ML_CLASSIFIER_URL: '{{ .data.ml_classifier_url | default "" }}'

search-service:
  environment: prod
  domain: meetinity.com
  replicaCount: 3
  autoscaling:
    minReplicas: 3
    maxReplicas: 6
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 50
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 60
      - type: Pods
        pods:
          metric:
            name: search_queries_per_second
          target:
            type: AverageValue
            averageValue: "40"
  resources:
    requests:
      cpu: 300m
      memory: 512Mi
    limits:
      cpu: 800m
      memory: 1Gi
  podDisruptionBudget:
    minAvailable: 2
  env:
    - name: SEARCH_NODES
      value: https://search.meetinity.com
    - name: SEARCH_VERIFY_CERTS
      value: "1"
    - name: SEARCH_TIMEOUT
      value: "10"
  vaultSecrets:
    - name: search-service-opensearch
      path: kv/data/prod/search-service/opensearch
      secretStoreRef:
        name: vault-prod
      target:
        template:
          type: Opaque
          data:
            SEARCH_USERNAME: '{{ .data.username | default "" }}'
            SEARCH_PASSWORD: '{{ .data.password | default "" }}'
