global:
  domain: staging.meetinity.com
  secretStores:
    default:
      name: vault-staging
      kind: ClusterSecretStore

shared:
  configMaps:
    platform-settings:
      data:
        FEATURE_FLAGS: "true"
        DEFAULT_TIMEZONE: "UTC"
  sealedSecrets:
    - name: platform-tls
      encryptedData:
        tls.crt: PLACEHOLDER_STAGING_CERT
        tls.key: PLACEHOLDER_STAGING_KEY

api-gateway:
  environment: staging
  domain: staging.meetinity.com
  replicaCount: 2
  image:
    tag: staging
  ingress:
    tlsSecretName: api-gateway-staging-tls
  autoscaling:
    minReplicas: 2
    maxReplicas: 6
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 65
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 75
      - type: Pods
        pods:
          metric:
            name: http_requests_per_second
          target:
            type: AverageValue
            averageValue: "25"
  resources:
    requests:
      cpu: 350m
      memory: 448Mi
    limits:
      cpu: 800m
      memory: 896Mi
  podDisruptionBudget:
    minAvailable: 1
  vpa:
    enabled: true
    updatePolicy:
      updateMode: "Off"
    resourcePolicy:
      containerPolicies:
        - containerName: "*"
          minAllowed:
            cpu: 250m
            memory: 384Mi
          maxAllowed:
            cpu: 2
            memory: 2Gi
  vaultSecrets:
    - name: api-gateway-env
      path: kv/data/staging/api-gateway/app
      secretStoreRef:
        name: vault-staging
      target:
        template:
          type: Opaque
          data:
            DATABASE_URL: '{{ .data.database_url }}'
            REDIS_URL: '{{ .data.redis_url }}'

user-service:
  environment: staging
  domain: staging.meetinity.com
  replicaCount: 2
  autoscaling:
    minReplicas: 2
    maxReplicas: 5
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 60
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 70
      - type: Pods
        pods:
          metric:
            name: user_profile_sync_per_second
          target:
            type: AverageValue
            averageValue: "10"
  resources:
    requests:
      cpu: 250m
      memory: 384Mi
    limits:
      cpu: 600m
      memory: 768Mi
  podDisruptionBudget:
    minAvailable: 1
  vpa:
    enabled: true
    updatePolicy:
      updateMode: "Off"
    resourcePolicy:
      containerPolicies:
        - containerName: "*"
          minAllowed:
            cpu: 200m
            memory: 320Mi
          maxAllowed:
            cpu: 1500m
            memory: 2Gi
  vaultSecrets:
    - name: user-service-db
      path: kv/data/staging/user-service/database
      secretStoreRef:
        name: vault-staging
      target:
        template:
          type: Opaque
          data:
            url: '{{ .data.url }}'

matching-service:
  environment: staging
  domain: staging.meetinity.com
  replicaCount: 2
  autoscaling:
    minReplicas: 2
    maxReplicas: 4
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 60
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 70
      - type: Pods
        pods:
          metric:
            name: matches_computed_per_second
          target:
            type: AverageValue
            averageValue: "12"
  resources:
    requests:
      cpu: 250m
      memory: 384Mi
    limits:
      cpu: 600m
      memory: 768Mi
  podDisruptionBudget:
    minAvailable: 1
  vpa:
    enabled: true
    updatePolicy:
      updateMode: "Off"
    resourcePolicy:
      containerPolicies:
        - containerName: "*"
          minAllowed:
            cpu: 200m
            memory: 320Mi
          maxAllowed:
            cpu: 1500m
            memory: 2Gi
  vaultSecrets:
    - name: matching-service-env
      path: kv/data/staging/matching-service/app
      secretStoreRef:
        name: vault-staging
      target:
        template:
          type: Opaque
          data:
            MATCHING_THRESHOLD: '{{ .data.matching_threshold | default "0.8" }}'

event-service:
  environment: staging
  domain: staging.meetinity.com
  replicaCount: 2
  autoscaling:
    minReplicas: 2
    maxReplicas: 5
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 60
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 70
      - type: Pods
        pods:
          metric:
            name: events_processed_per_second
          target:
            type: AverageValue
            averageValue: "20"
  resources:
    requests:
      cpu: 250m
      memory: 384Mi
    limits:
      cpu: 600m
      memory: 768Mi
  podDisruptionBudget:
    minAvailable: 1
  vpa:
    enabled: true
    updatePolicy:
      updateMode: "Off"
    resourcePolicy:
      containerPolicies:
        - containerName: "*"
          minAllowed:
            cpu: 200m
            memory: 320Mi
          maxAllowed:
            cpu: 1500m
            memory: 2Gi
  vaultSecrets:
    - name: event-service-env
      path: kv/data/staging/event-service/app
      secretStoreRef:
        name: vault-staging
      target:
        template:
          type: Opaque
          data:
            EVENT_CATALOG_URL: '{{ .data.catalog_url }}'
