global:
  environment: staging
  domain: staging.meetinity.com
  secretStores:
    default:
      name: vault-staging
      kind: ClusterSecretStore
      spec:
        provider:
          vault:
            server: https://vault.staging.meetinity.com
            auth:
              kubernetes:
                role: meetinity-staging

shared:
  configMaps:
    platform-settings:
      data:
        FEATURE_FLAGS: "true"
        DEFAULT_TIMEZONE: "UTC"
  vaultSecrets:
    - name: shared-database
      path: "kv/data/{{ .Values.global.environment }}/shared/database"
      target:
        name: meetinity-shared-database
        creationPolicy: Owner
        template:
          type: Opaque
    - name: shared-redis
      path: "kv/data/{{ .Values.global.environment }}/shared/redis"
      target:
        name: meetinity-shared-redis
        creationPolicy: Owner
        template:
          type: Opaque
    - name: platform-tls
      path: "kv/data/{{ .Values.global.environment }}/shared/tls/platform"
      target:
        name: platform-tls
        creationPolicy: Owner
        template:
          type: kubernetes.io/tls

api-gateway:
  environment: staging
  domain: staging.meetinity.com
  replicaCount: 2
  image:
    tag: staging
  ingress:
    tlsSecretName: api-gateway-staging-tls
  autoscaling:
    minReplicas: 2
    maxReplicas: 6
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 65
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 75
      - type: Pods
        pods:
          metric:
            name: http_requests_per_second
          target:
            type: AverageValue
            averageValue: "25"
  resources:
    requests:
      cpu: 350m
      memory: 448Mi
    limits:
      cpu: 800m
      memory: 896Mi
  podDisruptionBudget:
    minAvailable: 1
  vpa:
    enabled: true
    updatePolicy:
      updateMode: "Off"
    resourcePolicy:
      containerPolicies:
        - containerName: "*"
          minAllowed:
            cpu: 250m
            memory: 384Mi
          maxAllowed:
            cpu: 2
            memory: 2Gi
  env:
    - name: LOG_LEVEL
      value: info
  vaultSecrets:
    - name: api-gateway-tls
      path: "kv/data/staging/ingress/api-gateway"
      target:
        name: api-gateway-staging-tls
        creationPolicy: Owner
        template:
          type: kubernetes.io/tls

user-service:
  environment: staging
  domain: staging.meetinity.com
  replicaCount: 2
  autoscaling:
    minReplicas: 2
    maxReplicas: 5
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 60
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 70
      - type: Pods
        pods:
          metric:
            name: user_profile_sync_per_second
          target:
            type: AverageValue
            averageValue: "10"
  resources:
    requests:
      cpu: 250m
      memory: 384Mi
    limits:
      cpu: 600m
      memory: 768Mi
  podDisruptionBudget:
    minAvailable: 1
  vpa:
    enabled: true
    updatePolicy:
      updateMode: "Off"
    resourcePolicy:
      containerPolicies:
        - containerName: "*"
          minAllowed:
            cpu: 200m
            memory: 320Mi
          maxAllowed:
            cpu: 1500m
            memory: 2Gi

matching-service:
  environment: staging
  domain: staging.meetinity.com
  replicaCount: 2
  autoscaling:
    minReplicas: 2
    maxReplicas: 4
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 60
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 70
      - type: Pods
        pods:
          metric:
            name: matches_computed_per_second
          target:
            type: AverageValue
            averageValue: "12"
  resources:
    requests:
      cpu: 250m
      memory: 384Mi
    limits:
      cpu: 600m
      memory: 768Mi
  podDisruptionBudget:
    minAvailable: 1
  vpa:
    enabled: true
    updatePolicy:
      updateMode: "Off"
    resourcePolicy:
      containerPolicies:
        - containerName: "*"
          minAllowed:
            cpu: 200m
            memory: 320Mi
          maxAllowed:
            cpu: 1500m
            memory: 2Gi
  vaultSecrets:
    - name: matching-service-env
      path: kv/data/staging/matching-service/app
      secretStoreRef:
        name: vault-staging
      target:
        template:
          type: Opaque
          data:
            MATCHING_THRESHOLD: '{{ .data.matching_threshold | default "0.8" }}'

event-service:
  environment: staging
  domain: staging.meetinity.com
  replicaCount: 2
  autoscaling:
    minReplicas: 2
    maxReplicas: 5
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 60
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 70
      - type: Pods
        pods:
          metric:
            name: events_processed_per_second
          target:
            type: AverageValue
            averageValue: "20"
  resources:
    requests:
      cpu: 250m
      memory: 384Mi
    limits:
      cpu: 600m
      memory: 768Mi
  podDisruptionBudget:
    minAvailable: 1
  vpa:
    enabled: true
    updatePolicy:
      updateMode: "Off"
    resourcePolicy:
      containerPolicies:
        - containerName: "*"
          minAllowed:
            cpu: 200m
            memory: 320Mi
          maxAllowed:
            cpu: 1500m
            memory: 2Gi
  vaultSecrets:
    - name: event-service-env
      path: kv/data/staging/event-service/app
      secretStoreRef:
        name: vault-staging
      target:
        template:
          type: Opaque
          data:
            EVENT_CATALOG_URL: '{{ .data.catalog_url }}'
            MODERATION_SERVICE_URL: '{{ .data.moderation_url | default "http://moderation-service:8080" }}'

notification-service:
  environment: staging
  domain: staging.meetinity.com
  replicaCount: 2
  autoscaling:
    minReplicas: 2
    maxReplicas: 4
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 55
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 65
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 400m
      memory: 512Mi
  podDisruptionBudget:
    minAvailable: 1
  vaultSecrets:
    - name: notification-service-env
      path: kv/data/staging/notification-service/app
      secretStoreRef:
        name: vault-staging
      target:
        template:
          type: Opaque
          data:
            DATABASE_URL: '{{ .data.database_url | default "" }}'
            REDIS_URL: '{{ .data.redis_url | default "redis://redis:6379/0" }}'
            KAFKA_BOOTSTRAP_SERVERS: '{{ .data.kafka_bootstrap | default "kafka:9092" }}'
            KAFKA_NOTIFICATION_TOPIC: '{{ .data.kafka_topic | default "notifications.dispatch" }}'

moderation-service:
  environment: staging
  domain: staging.meetinity.com
  replicaCount: 2
  autoscaling:
    minReplicas: 2
    maxReplicas: 3
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 55
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 65
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 400m
      memory: 512Mi
  podDisruptionBudget:
    minAvailable: 1
  vaultSecrets:
    - name: moderation-service-env
      path: kv/data/staging/moderation-service/app
      secretStoreRef:
        name: vault-staging
      target:
        template:
          type: Opaque
          data:
            DATABASE_URL: '{{ .data.database_url | default "" }}'
            REDIS_URL: '{{ .data.redis_url | default "redis://redis:6379/1" }}'
            KAFKA_BOOTSTRAP_SERVERS: '{{ .data.kafka_bootstrap | default "kafka:9092" }}'
            KAFKA_MODERATION_TOPIC: '{{ .data.kafka_topic | default "moderation.events" }}'
            ML_CLASSIFIER_URL: '{{ .data.ml_classifier_url | default "" }}'
