{{- if .Values.global.secretStores }}
{{- $root := . }}
{{- range $key, $store := .Values.global.secretStores }}
{{- if $store.spec }}
{{- $kind := default "ClusterSecretStore" $store.kind }}
{{- $name := tpl (toString (default (printf "%s-%s" (include "meetinity.fullname" $root) $key) $store.name)) $root }}
{{- $namespace := "" }}
{{- if eq $kind "SecretStore" }}
  {{- $namespace = tpl (toString (default $root.Release.Namespace $store.namespace)) $root }}
{{- else if $store.namespace }}
  {{- $namespace = tpl (toString $store.namespace) $root }}
{{- end }}
apiVersion: external-secrets.io/v1beta1
kind: {{ $kind }}
metadata:
  name: {{ $name }}
  {{- if $namespace }}
  namespace: {{ $namespace }}
  {{- end }}
  {{- with $store.labels }}
  labels:
{{ tpl (toYaml .) $root | indent 4 }}
  {{- end }}
  {{- with $store.annotations }}
  annotations:
{{ tpl (toYaml .) $root | indent 4 }}
  {{- end }}
spec:
{{ tpl (toYaml $store.spec) $root | indent 2 }}
---
{{- end }}
{{- end }}
{{- end }}
