global:
  environment: ""
  domain: meetinity.com
  secretStores:
    default:
      name: meetinity-vault
      kind: ClusterSecretStore
      spec:
        provider:
          vault:
            server: https://vault.{{ .Values.global.environment | default "shared" }}.meetinity.com
            path: kv
            version: v2
            namespace: ""
            caBundle: ""
            auth:
              kubernetes:
                mountPath: kubernetes
                role: meetinity-{{ .Values.global.environment | default "shared" }}
                serviceAccountRef:
                  name: external-secrets
                  namespace: security
  database:
    secretName: meetinity-shared-database
    secretKeys:
      host: host
      readerHost: reader_host
      port: port
      name: database
      username: username
      password: password
      url: url
      readerUrl: reader_url
  redis:
    secretName: meetinity-shared-redis
    secretKeys:
      host: host
      readerHost: reader_host
      port: port
      username: username
      password: password
      url: url
      readerUrl: reader_url
  observability:
    tracing:
      enabled: false
      serviceName: ""
      propagators:
        - tracecontext
        - baggage
      sampler:
        type: parentbased_traceidratio
        ratio: 1.0
      exporter:
        endpoint: "http://jaeger-collector.observability.svc.cluster.local:4317"
        protocol: grpc
        headers: {}
      resourceAttributes: {}
      agent:
        enabled: false
        name: jaeger-agent
        image:
          repository: jaegertracing/jaeger-agent
          tag: "1.52.0"
          pullPolicy: IfNotPresent
        collector:
          host: jaeger-collector.observability.svc.cluster.local
          port: 14250
          protocol: grpc
        ports:
          - name: jaeger-udp-compact
            containerPort: 6831
            protocol: UDP
          - name: jaeger-udp-binary
            containerPort: 6832
            protocol: UDP
        env: []
        extraArgs: []
        resources: {}
        extraVolumeMounts: []
        extraVolumes: []
        livenessProbe: {}
        readinessProbe: {}

shared:
  configMaps:
    platform-settings:
      annotations: {}
      data:
        FEATURE_FLAGS: "false"
        DEFAULT_TIMEZONE: "UTC"
  sealedSecrets: []
  vaultSecrets:
    - name: shared-database
      path: "kv/data/{{ .Values.global.environment }}/shared/database"
      target:
        name: meetinity-shared-database
        creationPolicy: Owner
        template:
          type: Opaque
    - name: shared-redis
      path: "kv/data/{{ .Values.global.environment }}/shared/redis"
      target:
        name: meetinity-shared-redis
        creationPolicy: Owner
        template:
          type: Opaque
