{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "notification-service.fullname" . }}
  labels:
    {{- include "notification-service.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ printf "%s.%s.%s" .Values.ingress.subdomain .Values.environment .Values.domain }}
      http:
        paths:
          {{- range .Values.ingress.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "notification-service.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
  {{- if .Values.ingress.tlsSecretName }}
  tls:
    - secretName: {{ .Values.ingress.tlsSecretName }}
      hosts:
        - {{ printf "%s.%s.%s" .Values.ingress.subdomain .Values.environment .Values.domain }}
  {{- end }}
{{- end }}
