apiVersion: v1
kind: Namespace
metadata:
  name: meetinity-dev
  labels:
    app.kubernetes.io/part-of: meetinity
    meetinity.io/environment: dev
    networking.meetinity.io/ingress-allowed: "true"
  annotations:
    meetinity.io/purpose: development workloads for Meetinity
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: meetinity-dev-compute
  namespace: meetinity-dev
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "6"
    limits.memory: 12Gi
    pods: "40"
    services.loadbalancers: "2"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: meetinity-dev-defaults
  namespace: meetinity-dev
spec:
  limits:
    - type: Container
      default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      max:
        cpu: "2"
        memory: 2Gi
      min:
        cpu: 50m
        memory: 64Mi
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: meetinity-dev-default
  namespace: meetinity-dev
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              meetinity.io/environment: dev
        - namespaceSelector:
            matchLabels:
              networking.meetinity.io/ingress-allowed: "true"
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              meetinity.io/environment: dev
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80
