fullnameOverride: fluent-bit

serviceAccount:
  create: true
  name: fluent-bit
  annotations: {}

rbac:
  create: true

podAnnotations:
  fluentbit.io/exclude-namespace: kube-system

podLabels:
  stack: logging

daemonSet:
  enabled: true
  updateStrategy:
    type: RollingUpdate
  tolerations:
    - operator: Exists
  nodeSelector:
    kubernetes.io/os: linux
  podSecurityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  volumes:
    - name: varlog
      hostPath:
        path: /var/log
    - name: varlibdockercontainers
      hostPath:
        path: /var/lib/docker/containers
        type: DirectoryOrCreate
    - name: fluent-bit-config
      configMap:
        name: fluent-bit-config
  volumeMounts:
    - name: varlog
      mountPath: /var/log
    - name: varlibdockercontainers
      mountPath: /var/lib/docker/containers
      readOnly: true
    - name: fluent-bit-config
      mountPath: /fluent-bit/etc/conf.d
      readOnly: true

daemonSetVolumes:
  - name: positions
    hostPath:
      path: /var/lib/fluent-bit
      type: DirectoryOrCreate

daemonSetVolumeMounts:
  - name: positions
    mountPath: /var/lib/fluent-bit

config:
  service: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020

  inputs: |
    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Parser            docker
        Tag               kube.*
        Refresh_Interval  5
        Mem_Buf_Limit     50MB
        Skip_Long_Lines   On
        DB                /var/lib/fluent-bit/kube.db
        DB.Sync           Normal

  filters: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_Tag_Prefix     kube.var.log.containers.
        Kube_Meta_Cache_TTL 300
        Merge_Log           On
        Keep_Log            Off
        Annotations         On
        Labels              On
        Kubelet_Port        10250
        Buffer_Size         0

    [FILTER]
        Name          modify
        Match         kube.*
        Condition     Key_Value_Equals log.level DEBUG
        Remove        log.level

  outputs: |
    [OUTPUT]
        Name            forward
        Match           kube.*
        Host            logstash.logging.svc.cluster.local
        Port            5044
        TLS             On
        TLS.Verify      Off
        Retry_Limit     False

extraParsers: |
  [PARSER]
      Name        docker
      Format      json
      Time_Key    time
      Time_Format %Y-%m-%dT%H:%M:%S.%L%z
      Time_Keep   On

