installCRDs: true

replicaCount: 2

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

webhook:
  timeoutSeconds: 10

prometheus:
  enabled: true
  servicemonitor:
    enabled: true
