apiVersion: v2
name: search-service
description: Deploys the Meetinity Search service.
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: common
    version: 0.1.0
    repository: "file://../common"
